#+title Emacs configuration via org-babel
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

This is and probably always will be a work in progress! :-) 

* Manual steps
There are some steps that require some manual intervention.

** Aspell - spellcheck

~aspell~ needs to be install via ~brew~ / ~apt~ however!

** lsp 
Installing specfic LSP language servers.
Clojure can be done from within emacs vai ~M-x lsp-install-server~

Some langages require extra setup...

* hacks for osx...
#+begin_src emacs-lisp
  (setq image-types (cons 'svg image-types))
#+end_src

* Vanilla UI configuration

#+begin_src emacs-lisp
  ;; Don't show the splash screen
  (setq inhibit-startup-message t)

  ;; flash on error / warnings
  (setq visible-bell t)

  ;; turn off some gui features
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (menu-bar-mode -1)

  (display-fill-column-indicator-mode -1)

  ;; highlight the current line
  (hl-line-mode t)
  ;; Add some space 
  (set-fringe-mode 0)

   ;; line numbers
  ;; (global-display-line-numbers-mode t)

  ;; show the column in mode line
  (column-number-mode 1)

  ;; wrap lines everywhere
  (global-visual-line-mode 1)

  ;; hide the mode line... lets try this
  ;; (global-hide-mode-line-mode)

  ;; for osx 
   (setq frame-resize-pixelwise t)

  ;; (setq right-margin-width 0)
  ;; (setq left-margin-width 0)

  ;; (set-window-buffer nil (current-buffer))


  (add-to-list 'default-frame-alist '(internal-border-width . 10))
  (add-to-list 'default-frame-alist '(alpha 90 90))


#+end_src

* Run emcas as a server?
Don't do it this way...
Better to use the --daemon flag 
#+begin_src emacs-lisp
;;  (server-start)
#+end_src

* Package management

Tell emacs where to search for external packages
#+begin_src emacs-lisp
    ;; Initialize package sources and ensure use-package
    (require 'package)

    (setq package-archives '(("melpa"  . "https://melpa.org/packages/")
			     ("org"    . "https://orgmode.org/elpa/")
			     ("elpa"   . "https://elpa.gnu.org/packages/")
			     ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

    (package-initialize) 

    (unless (and package-archive-contents (package-installed-p 'use-package))
      (package-refresh-contents)
      (package-install 'use-package))
      (eval-when-compile (require 'use-package))

    (require 'use-package)
    ;; ensure all use package packages are downlaoded
    (setq use-package-always-ensure t)

    ;; quelpa is a tool to compile and install Emacs Lisp packages locally from local or remote source code. https://github.com/quelpa/quelpa

    (use-package quelpa)

#+end_src

** Straight

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name
	  "straight/repos/straight.el/bootstrap.el"
	  (or (bound-and-true-p straight-base-dir)
	      user-emacs-directory)))
	(bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	   'silent 'inhibit-biscuits)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

* Theme
Make it look good :-)

I like monokai-theme makes me feel like I'm using sublime text 2 again in university.

#+begin_src emacs-lisp
  (use-package monokai-theme)
  ;; (load-theme 'monokai t)
#+end_src



I really like monokai-theme as the default but with direct light on my monitor it is hard to read. [[https://github.com/doomemacs/themes][Doom themes]] are awesome and provide a choice of lighter themes to swap to when needed.


#+begin_src emacs-lisp
    (use-package doom-themes
      :config
      ;; Global settings (defaults)
      (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
	    doom-themes-enable-italic t) ; if nil, italics is universally disabled
      ;; (load-theme 'doom-one-light t)

      ;; Enable flashing mode-line on errors
      (doom-themes-visual-bell-config)
      ;; Enable custom neotree theme (all-the-icons must be installed!)
      (doom-themes-neotree-config)
      ;; or for treemacs users
      (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
      (doom-themes-treemacs-config)
      ;; Corrects (and improves) org-mode's native fontification.
      (doom-themes-org-config))

  (load-theme 'doom-nord t)

#+end_src

Icons!

#+begin_src emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p))

  (all-the-icons-install-fonts t)
#+end_src

* Mode line

Turns out Doom also has the best easy drop in mode line package with [[https://github.com/seagle0128/doom-modeline#use-package][doom-modeline]]. 
#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
#+end_src

* Start up buffers
What to show when opening Emacs without specifying a file. 

There are packages to define what gets shown when Emacs initially loads. Actually I think I might not actually even need a package I'm sure there is some configuration.

Ideas :
- Agenda + prompt to start a journal entry if there isn't one for the day say far probably via yasnippet or an org capture template
- Something similar to Doom which gives you a few sensible links, recent projects / files etc.
- Email inbox
- Hacker news / Reddit / RSS feed lots of options 


#+begin_src emacs-lisp

  ;; Okay emacs dashboard just works and is great! 

  (use-package page-break-lines)

  (use-package dashboard
      :config
      (dashboard-setup-startup-hook))

  (setq dashboard-items '((agenda . 10)
			  (recents  . 5)
			  (projects . 5)
			  (bookmarks . 5)
			  (registers . 5)))

  (setq dashboard-match-agenda-entry "important")
  
  ;; for emacsclient 
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))

  ;; Set the title
  (setq dashboard-banner-logo-title "Welcome to Emacs Dashboard")
  ;; Set the banner
  (setq dashboard-startup-banner "~/.emacs.d/mountain.png")
  ;; Value can be
  ;; - nil to display no banner
  ;; - 'official which displays the official emacs logo
  ;; - 'logo which displays an alternative emacs logo
  ;; - 1, 2 or 3 which displays one of the text banners
  ;; - "path/to/your/image.gif", "path/to/your/image.png" or "path/to/your/text.txt" which displays whatever gif/image/text you would prefer
  ;; - a cons of '("path/to/your/image.png" . "path/to/your/text.txt")

  ;; Content is not centered by default. To center, set
  (setq dashboard-center-content t)

  ;; Shortcut "jump" indicators for each section
  (setq dashboard-show-shortcuts t)



#+end_src

* PATH configuration
Ensure emacs uses the shell path so we can access user bins
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
     :config (exec-path-from-shell-initialize))
#+end_src

* Ivy completion - via counsel

Ivy is a completion framework which provies a lot of extra functionality / niceness over the default ido. 

Counsel and Swiper are built on top of Ivy. Swiper is for searching and Ivy provides a completion framework. 

#+begin_src emacs-lisp
  (use-package counsel)
  (ivy-mode 1) ;; Ivy completion everywhere

  ;;;; recomended defaults - https://oremacs.com/swiper/#basic-customization
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq ivy-use-selectable-prompt t)
  (setq enable-recursive-minibuffers t)
  
  ;;;; recomended counsel/ivy/swiper  key bindings
  (global-set-key (kbd "C-s") 'swiper-isearch)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "M-y") 'counsel-yank-pop)
  (global-set-key (kbd "<f1> f") 'counsel-describe-function)
  (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
  (global-set-key (kbd "<f1> l") 'counsel-find-library)
  (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
  (global-set-key (kbd "<f2> j") 'counsel-set-variable)
  (global-set-key (kbd "C-x b") 'counsel-switch-buffer)
  (global-set-key (kbd "C-c v") 'ivy-push-view)
  (global-set-key (kbd "C-c V") 'ivy-pop-view)

#+end_src

* Rich annotations with Marginalia
Add a desecration / summary of the commands shown in the mini buffer.
#+begin_src emacs-lisp
  (use-package marginalia
    ;; Either bind `marginalia-cycle` globally or only in the minibuffer
    :bind (("M-A" . marginalia-cycle)
	   :map minibuffer-local-map
	   ("M-A" . marginalia-cycle))

    ;; The :init configuration is always executed (Not lazy!)
    :init
    ;; Must be in the :init section of use-package such that the mode gets
    ;; enabled right away. Note that this forces loading the package.
    (marginalia-mode))
#+end_src

* Which key - suggest key chord completion
Opens the mini buffer with suggestions of what valid key chords are available 
#+begin_src emacs-lisp
  (use-package which-key
    :defer 0
    :diminish which-key-modeq
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))
#+end_src

* Projectile - project management
Emacs project management tools based on version control or certain build tools like package.json I believe. 
https://docs.projectile.mx/projectile/index.html
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :diminish projectile-mode
    :init
    (projectile-mode +1)
    :bind (:map projectile-mode-map
		("C-c p" . projectile-command-map))
    :init
    (setq projectile-project-search-path '("~/Projects/")))

  (use-package counsel-projectile
    :after projectile
    :config (counsel-projectile-mode))
#+end_src
** TODO counsel keybindings not properly set up

* Magit - git wrapper

Emacs does Git really well with Magit. 

#+begin_src emacs-lisp
  (use-package magit
    :commands magit-status)
#+end_src

* flycheck - linting / syntax checking etc
https://www.flycheck.org/en/latest/
#+begin_src emacs-lisp
  (use-package flycheck
    :init (global-flycheck-mode))

#+end_src

* Spellchecking

Please fix my dyslexia computer! 

#+begin_src emacs-lisp
  (add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'prog-mode-hook 'flyspell-prog-mode)

  (setq ispell-dictionary "en_GB")
  (setq ispell-program-name "aspell")
  (setq ispell-silently-savep t)

  (use-package flyspell-correct
    :after flyspell
    :bind (:map flyspell-mode-map ("C-;" . flyspell-correct-wrapper)))

  (use-package flyspell-correct-ivy
    :after flyspell-correct)

  (use-package flyspell-correct-popup
    :after flyspell-correct)
#+end_src
* LSP mode - IDE features

#+begin_src emacs-lisp
(use-package yaml-mode)  
#+end_src


#+begin_src emacs-lisp
  (use-package lsp-mode
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l"
	  gc-cons-threshold 100000000
	  read-process-output-max (* 1024 1024))
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
	   (clojure-mode . lsp)
	   (terraform-mode . lsp)
	   ;; if you want which-key integration
	   (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp)

  ;; optionally
  (use-package lsp-ui :commands lsp-ui-mode)
  ;; if you are ivy user
  (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
  (use-package lsp-treemacs :commands lsp-treemacs-errors-list)

  ;; optionally if you want to use debugger
  ;;  (use-package dap-mode)
  ;; (use-package dap-LANGUAGE) to load the dap adapter for your language

  (lsp-install-server nil 'clojure-lsp)
  
#+end_src

* Yasnippet
[[https://joaotavora.github.io/yasnippet/][Yet another snippet extension]]

#+begin_quote
YASnippet is a template system for Emacs. It allows you to type an abbreviation and automatically expand it into function templates.
#+end_quote

#+begin_src emacs-lisp
  (use-package yasnippet)
  (use-package yasnippet-snippets)

  (yas-global-mode 1)
#+end_src

* TIDE - typescript IDE for Emacs
[[https://github.com/ananthakumaran/tide][TypeScript Interactive Development Environment for Emacs]]:

#+begin_src emacs-lisp
  (use-package company)
  (use-package tide)
  (use-package web-mode)

  (defun setup-tide-mode ()
    (interactive)
    (tide-setup)
    (flycheck-mode +1)
    (setq flycheck-check-syntax-automatically '(save mode-enabled))
    (eldoc-mode +1)
    (tide-hl-identifier-mode +1)
    ;; company is an optional dependency. You have to
    ;; install it separately via package-install
    ;; `M-x package-install [ret] company`

    (setq tide-format-options
	  '(:insertSpaceAfterFunctionKeywordForAnonymousFunctions t
	    :indentSize 2
	    :tabSize 2
	    :placeOpenBraceOnNewLineForFunctions nil
	    : ))

    (setq typescript-indent-level 2)
    (company-mode +1))

  ;; aligns annotation to the right hand side
  (setq company-tooltip-align-annotations t)

  ;; formats the buffer before saving
  (add-hook 'before-save-hook 'tide-format-before-save)
  (add-hook 'typescript-mode-hook #'setup-tide-mode)

  ;; tsx
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
  (add-hook 'web-mode-hook
	    (lambda ()
	      (when (string-equal "tsx" (file-name-extension buffer-file-name))
		(setup-tide-mode))))
  ;; enable typescript-tslint checker
  (flycheck-add-mode 'typescript-tslint 'web-mode)

  ;; javascript 
  (add-hook 'js2-mode-hook #'setup-tide-mode)
  ;; configure javascript-tide checker to run after your default javascript checker
  (flycheck-add-next-checker 'javascript-eslint 'javascript-tide 'append)

  ;; jsx
  (add-to-list 'auto-mode-alist '("\\.jsx\\'" . web-mode))
  (add-hook 'web-mode-hook
	    (lambda ()
	      (when (string-equal "jsx" (file-name-extension buffer-file-name))
		(setup-tide-mode))))
  ;; configure jsx-tide checker to run after your default jsx checker
  (flycheck-add-mode 'javascript-eslint 'web-mode)
  (flycheck-add-next-checker 'javascript-eslint 'jsx-tide 'append)

#+end_src

* Clojure packages
                             
#+begin_src emacs-lisp
  (use-package rainbow-delimiters)
  (use-package smartparens)
  (use-package idle-highlight-mode) 
  (use-package flycheck-clojure)
  (use-package flycheck-clj-kondo)

  (use-package flycheck-pos-tip
    :after flycheck)

  (eval-after-load 'flycheck
    '(setq flycheck-display-errors-function #'flycheck-pos-tip-error-messages))


  (use-package flycheck-clojure
    :defer t
    :commands (flycheck-clojure-setup)               ;; autoload
    :config
    (eval-after-load 'flycheck
      '(setq flycheck-display-errors-function #'flycheck-pos-tip-error-messages))
    (add-hook 'after-init-hook #'global-flycheck-mode))

  (use-package clojure-mode
    :config
    (require 'flycheck-clj-kondo)
    :mode (("\\.clj\\'" . clojure-mode)
	   ("\\.edn\\'" . clojure-mode))
    :init
    (add-hook 'clojure-mode-hook #'subword-mode)           
    (add-hook 'clojure-mode-hook #'smartparens-mode)       
    (add-hook 'clojure-mode-hook #'rainbow-delimiters-mode)
    (add-hook 'clojure-mode-hook #'eldoc-mode)             
    (add-hook 'clojure-mode-hook #'idle-highlight-mode))

  (use-package clj-refactor
    :defer t
    :ensure t
    :diminish clj-refactor-mode
    :config (cljr-add-keybindings-with-prefix "C-c C-m"))

  (use-package cider
    :ensure t
    :defer t
    :init (add-hook 'cider-mode-hook #'clj-refactor-mode)
    :diminish subword-mode
    :config
    (setq nrepl-log-messages t                  
	  cider-repl-use-clojure-font-lock t    
	  cider-prompt-save-file-on-load 'always-save
	  cider-font-lock-dynamically '(macro core function var)
	  nrepl-hide-special-buffers t            
	  cider-overlays-use-font-lock t)
    (flycheck-clojure-setup)
    (cider-repl-toggle-pretty-printing))
#+end_src

* Terraform packages
#+begin_src emacs-lisp
    (use-package terraform-mode
      :mode (("\\.tf\\'" . terraform-mode)
	     ("\\.tfvars\\'" . terraform-mode))
      :custom (terraform-indent-level 2)
  ;; terraform-ls for stable language server
      :hook (terraform-mode . lsp)
      ) 
#+end_src

* Org mode - very meta!!!

[[https://orgmode.org/][Org Mode]] is really hard to describe as it does /a lot/ and has a load of extensions.  At it's core Org Mode is an outlining tool.  It defines headers that you can nest and open / collapse.  Built on top of that is a system for scheduling, having different work states like TODO / DONE etc, agendas and exporting files to different formats.  Org sort of does a bit of everything. 

** Fundamental key binds 
#+begin_src emacs-lisp
    ;; org-mode
    (global-set-key (kbd "C-c l") #'org-store-link)
    (global-set-key (kbd "C-c a") #'org-agenda)
    (global-set-key (kbd "C-c c") #'org-capture)

#+end_src

** Org agenda path

#+begin_src emacs-lisp
    (setq org-agenda-files (directory-files-recursively "~/org/" "\\.org$"))

#+end_src

** Org todo keywords
#+begin_src emacs-lisp
  (setq org-todo-keywords
	'((sequence "TODO(t)" "WAIT(w@/!)" "BOOKED(b!)" "BLOG(b)" "PROJECT(p)" "|" "DONE(d!)" "CANCELED(c@)")))
  (setq org-log-into-drawer t)
#+end_src

** Org Contrib: checklist
#+begin_src emacs-lisp
  (use-package org-contrib)
  (require 'org-checklist) ;; requires a2ps to be installed
#+end_src


** Org refile
Moving headlines around

#+begin_src emacs-lisp
  (setq org-refile-targets '(("~/org/personal/personal.org" :maxlevel . 2)))
#+end_src

** Org Babel
Languages to load 
#+begin_src emacs-lisp
  (eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((clojure . t)
     (emacs-lisp . t)
     (shell . t))))
#+end_src

Org Babel Clojure back-end - defer to cider which requires jack in 
#+begin_src emacs-lisp
  (setq org-babel-clojure-backend 'cider)
#+end_src

Auto tangle - saves you needing to explicitly tangle org files. 
#+begin_src emacs-lisp
  ;; (use-package org-auto-tangle
  ;; :defer t
  ;; :hook (org-mode . org-auto-tangle-mode))

  ;; (setq org-auto-tangle-default t)
#+end_src

** Org modern - styling package

#+begin_src emacs-lisp
  ;;;; org modern - clean theme 
  (use-package org-modern
    :init
    (add-hook 'org-mode-hook #'org-modern-mode)
    (add-hook 'org-agenda-finalize-hook #'org-modern-agenda))

  ;; Choose some fonts
  ;; (set-face-attribute 'default nil :family "Iosevka")
  ;; (set-face-attribute 'variable-pitch nil :family "Iosevka Aile")
  ;; (set-face-attribute 'org-modern-symbol nil :family "Iosevka")

  (modify-all-frames-parameters
   '((right-divider-width . 40)))
  (dolist (face '(window-divider
		  window-divider-first-pixel
		  window-divider-last-pixel))
    (face-spec-reset-face face)
    (set-face-foreground face (face-attribute 'default :background)))
  (set-face-background 'fringe (face-attribute 'default :background))

  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t

   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-ellipsis "↯"

   ;; Agenda styling
   org-agenda-tags-column 0
   org-agenda-block-separator ?─
   org-agenda-time-grid
   '((daily today require-timed)
     (800 1000 1200 1400 1600 1800 2000)
     " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
   org-agenda-current-time-string
   " now ─────────────────────────────────────────────────")

#+end_src

** Inline images
Don't use the real image width for inline images - images are rendered WAAAAAY too large to be useful in org files. 
#+begin_src emacs-lisp
  (setq org-image-actual-width 400)
#+end_src

** Centre text while working with org files
#+begin_src emacs-lisp

  (use-package visual-fill-column
    :hook (org-mode .  (lambda ()
			 (setq visual-fill-column-width 100
			       visual-fill-column-center-text t)
			 (visual-fill-column-mode 1)
			 )))

  #+end_src

** Org Kanban
#+begin_src emacs-lisp
  (use-package org-kanban)
#+end_src
** Capture Templates

#+begin_src emacs-lisp

  (setq org-capture-templates
    '(("i" "Inbox" entry (file+headline "~/org/personal/personal.org" "Inbox")
       "* TODO %?\n  %i\n  %a" :empty-lines 1)
      ("j" "Journal" entry (file+olp+datetree "~/org/personal/journal.org")
       "* %?\nEntered on %U\n  %i\n" :empty-lines 1)
      ("J" "Journal entry at time" entry (file+olp+datetree "~/org/personal/journal.org")
       "* %T %?\n%i\n" :time-prompt t :empty-lines 1)

      ("w" "work")
      ("wj" "Work Journal" entry (file+olp+datetree "~/org/work/work-journal.org")
       "* %?\nEntered on %U\n  %i\n  %a" :empty-lines 1)
      ("wJ" "Work Journal entry at time" entry (file+olp+datetree "~/org/work/work-journal.org")
       "* %T %?\n%i\n%a" :time-prompt t :empty-lines 1)

      ))

#+end_src

*** Capture templates for Hugo blog posts
#+begin_src emacs-lisp
  ;; Populates only the EXPORT_FILE_NAME property in the inserted heading.
  (with-eval-after-load 'org-capture
    (defun org-hugo-new-subtree-post-capture-template ()
      "Returns `org-capture' template string for new Hugo post.
  See `org-capture-templates' for more information."
      (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
	     (fname (org-hugo-slug title)))
	(mapconcat #'identity
		   `(
		     ,(concat "* TODO " title)
		     ":PROPERTIES:"
		     ,(concat ":EXPORT_FILE_NAME: " fname)
		     ":END:"
		     "%?\n")          ;Place the cursor here finally
		   "\n")))

    (add-to-list 'org-capture-templates
		 '("h" "Hugo post"))
    (add-to-list 'org-capture-templates    
		 '("hc" "Coding Clojure"
		   entry
		   (file+olp "~/org/blog-posts/coding-clojure/coding-clojure.org" "posts")
		   (function org-hugo-new-subtree-post-capture-template)))
    (add-to-list 'org-capture-templates    
		 '("ht" "they.es"
		   entry
		   (file+olp "~/org/blog-posts/they.es/personal-tech-blog.org" "posts")
		   (function org-hugo-new-subtree-post-capture-template))))

#+end_src

** Expert dispatch extension - ox hugo 
#+begin_src emacs-lisp
;; export to hugo 
  (use-package ox-hugo
    :pin melpa 
    :after ox)

#+end_src

** Org google cal sync

Get org and google calendar playing together. This is a bit of a WIP in project that requires a fair amountu of external configuration / setup.  However I /really/ like seeing my google calendar events synced into my org agenda.

https://github.com/kidd/org-gcal.el
#+begin_src emacs-lisp

  (use-package request)
  (use-package alert)
  (use-package persist)
  (use-package aio) ;; async / await 
  ;;(use-package oauth2)  not in mepla yet use fork
  (quelpa
   '(oauth2-auto
     :fetcher git
     :url "https://github.com/telotortium/emacs-oauth2-auto.git"))


  (use-package org-gcal)

  (setenv "GPG_AGENT_INFO")

  (setq plstore-cache-passphrase-for-symmetric-encryption t)

#+end_src


** Org TWBS - quick html view
Export org-mode docs as HTML compatible with Twitter Bootstrap.
Pretty and quick exports - useful for sharing org files with other people in a pretty way. 
https://github.com/marsmining/ox-twbs 
#+begin_src emacs-lisp
  (use-package ox-twbs)
#+end_src

** Org Roam - note taking - knowledge base

#+begin_src emacs-lisp
  (use-package org-roam
    :custom
    (org-roam-directory (file-truename "~/org/roam/"))
    (org-roam-capture-templates
     '(("d" "default" plain
	"%?"
	:if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title} \n\n\n#+print_bibliography:")
	:unnarrowed t)))
    :bind (("C-c n l" . org-roam-buffer-toggle)
	   ("C-c n f" . org-roam-node-find)
	   ("C-c n g" . org-roam-graph)
	   ("C-c n i" . org-roam-node-insert)
	   ("C-c n c" . org-roam-capture)
	   ;; Dailies
	   ("C-c n j" . org-roam-dailies-capture-today))
    :config
    ;; If you're using a vertical completion framework, you might want a more informative completion interface
    (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-db-autosync-mode)
    ;; If using org-roam-protocol
    ;;(require 'org-roam-protocol)
    )



#+end_src

*** TODO Investigate org protocol 

*** TODO Investigate org roam UI 

#+begin_src emacs-lisp
  (use-package org-roam-ui
  :straight
    (:host github :repo "org-roam/org-roam-ui" :branch "main" :files ("*.el" "out"))
    :after org-roam
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src

*** TODO Investigate mobile syncing 

** Org cite

#+begin_src emacs-lisp
  (require 'oc-natbib)
  (require 'oc-biblatex)
  (setq org-cite-export-processors '((latex biblatex)
				     (t basic)))
  (setq org-cite-global-bibliography '("~/org/roam/references/master-lib.bib"))

#+end_src

* Vterm - terminal

[[https://github.com/akermu/emacs-libvterm][Vterm]] is a great terminal emulator that runs inside of Emacs. It feels the closest to a regular terminal application inside of Emacs and is also really fast. 

[[https://github.com/suonlight/multi-vterm][Multi-vterm]] enables multiple Vterm buffers 

#+begin_src emacs-lisp
  (use-package vterm)

  (use-package hide-mode-line)

  (use-package multi-vterm
    :config
    (add-hook 'vterm-mode-hook
	      (lambda () 
		(hide-mode-line-mode)
		)))

#+end_src

